### ISSUE TITLE
Minor improvements of CLI output

### ISSUE THREAD

**Issue by tschale** [Getdeck/getdeck#117]
### What is the new feature about?

- When no deckfile is specified, i.e. running with `deck get .`, the output is `[INFO] Reading Deckfile: .`. This could be changed to `[INFO] Reading Deckfile: deck.yaml`, as `deck.yaml` is the default.
- When a local cluster already exists, the output of `get` is `[INFO] Cluster already exists, starting it`. This could be enhanced so that the clustername is included, such as it is when a new cluster is created.

### Why would such a feature be important to you?

Minor output improvements in the vein of "explicit is more implicit"

**Comment by buschNT** [comment]
This issue was solved with version 0.11.1

**Comment by tschale** [comment]
I can confirm the first one, however when running `deck get` when the cluster already exists, I still get following output:
```
[INFO] Cluster already exists, starting it
```

**Comment by buschNT** [comment]
> I can confirm the first one, however when running deck get when the cluster already exists, I still get following output:

True, furthermore the `[INFO] Reading Deckfile: .` still exists when there is no deck.yml in the cwd.

**Comment by tschale** [comment]
I found another small thing, what do you think about adding `http://` to the ingress output? Currently it's the following:
```
[INFO] Ingress: foo.127.0.0.1.nip.io -> /admin
[INFO] Ingress: foo.127.0.0.1.nip.io -> /
```
If it would be `http://foo.127.0.0.1.nip.io` it would be directly clickable from the terminal. Of course one might have https configured, however I would expect there to be a redirect to https from http.

**Comment by tschale** [comment]
Just another thing that I realized. I was using the `-I` flag to install the deckfile-resources into my current kubecontext, which was a GKE cluster. In the output I also got `[INFO] Cluster already exists, starting it`. 

When using the `-I` flag, getdeck won't be able to start a cluster, or would it? Shall we change the output of that line completely, or even omit it when using `-I`?
