### ISSUE TITLE
deck get ...geyfra-demos.git fails on openSUSE

### ISSUE THREAD

**Issue by rolandg333** [Getdeck/getdeck#85]
INFO] Deck version: 0.9.5

$ deck  get https://github.com/gefyrahq/gefyra-demos.git

fails on openSuse with error message: 

`[CRITICAL] There was an error running deck: The command '/bin/sh -c addgroup -g ${GROUP_ID} -S tooler && adduser -u ${USER_ID} -S tooler -G tooler' returned a non-zero code: 1`

'addgroup' and 'adduser' are commands not available on all kind of linux distributions. 
porting to 'groupadd' and 'useradd' might be a good solution ( an should  be easy )

**Comment by Schille** [comment]
Hi @rolandg333 
Thank you for bringing this up.

The `tooler` (a container image) component is built on each system when running for the first time. The code for the _adduser_/_addgroup_ is this:
https://github.com/Getdeck/getdeck/blob/main/getdeck/sources/tooler.py#L86-L89
Currently, there is a branch for Windows and Mac; all Linux distros fall in the `else` branch.

**Comment by rolandg333** [comment]
Hi Michael,

i already found the sources, and the place where i would change.

but how do i build the whole project, or test any change by myself.

**Comment by buschNT** [comment]
Hi @rolandg333 ,

currently, you would still have to test your changes manually. We are actively working on adding a better test setup and more tests, but this takes a little bit more time.

I develop using a venv. Then I run getdeck commands with the venv activated using `python -m getdeck <COMMAND>` and manually test changes.
Or in case you are using VSCode, you can add the following to the _configurations_ in your _launch.json_:

```
        {
            "name": "development",
            "type": "python",
            "request": "launch",
            "module": "getdeck",
            "justMyCode": true,
            "args": [
                "get",
                "<DECKFILE>"
            ]
        },
```
Sometimes you might have to add the `"cwd": ` option, too, depending on where the deck file is located.

In order to test changes on the tooler, **you have to delete your local tooler image** in order to trigger a rebuild:
https://github.com/Getdeck/getdeck/blob/368b0c2debdc2f5092377f20ed309d19c807040c/getdeck/sources/tooler.py#L27-L30

I created an issue regarding a development setup documentation: https://github.com/Getdeck/getdeck/issues/86

Hopefully my short development description helps, if not feel free to point out what's unclear.

**Comment by Z02X** [comment]
Mentioning this here so my issue #93 can be closed as duplicate. I believe the issue could be caused when the id's are 0, sutch as when run as root. I don't think it could be the commands missing.

**Comment by rolandg333** [comment]
the fix for #101 is not working on openSUSE. i face still the same error

i've added a debug line and found:
[DEBUG] Tooler build_args: {'USER_ID': '1000', 'GROUP_ID': '100'}

because:
$ id 
uid=1000(roland) gid=100(users) Gruppen=100(users),459(libvirt),460(qemu),463(docker),482(systemd-journal),487(kvm),496(wheel)

the docker image  quay.io/getdeck/tooler  is based on alpine linux; a group with gid 100 is already existing. the addgroup call fails.

when I override gid in 
--- a/getdeck/sources/tooler.py
+++ b/getdeck/sources/tooler.py
@@ -79,6 +79,7 @@ def build_user_container(config: ClientConfiguration):
     if sys.platform != "win32":
         uid = os.getuid() or 1000
         gid = os.getgid() or 1000
+        gid = 1000
     else:
         uid = 1000
         gid = 1000

the tooler image gets created.

**Comment by Schille** [comment]
@rolandg333 thank you for your eager testing and your results.
I will think about another solution then.

The point of mapping the user and group id is for the correct ownership of the generated files (in a mounted volume) later in the process. We want to write the files from within the docker container with the same user identity as the user calling `deck`.

**Comment by Schille** [comment]
I added a check to the image build process: if userid or groupid exist, they are not created. I assume the userid and groupid are used to map file permissions in the shared volumes to the host system.
@rolandg333 are you able to test the code in branch "_fix/#85-1_" if this is working for you?

**Comment by Schille** [comment]
This is included in version 0.11.0 of deck.

**Comment by Schille** [comment]
Oh well. 🫣 I haven't had the group assignment in mind for the user creation.
Your version looks much better. Will you create a PR for it? I would appreciate it.

**Comment by rolandg333** [comment]
how can i do this ? 
I cannot push on the branch.

**Comment by Schille** [comment]
You need to click the fork button an then create a Pull request from your repo onto this.

**Comment by rolandg333** [comment]
done; can you see the PR ?

**Comment by Z02X** [comment]
I probably should have said something because I tested locally. But on some distros you would still get:

```
'deck-tooler:version' returned non-zero exit status 1: b'Error: stat /output/{helm chaart}/templates: permission denied\n\nUse --debug flag to render out invalid YAML
```
if you just use 1000.

**Comment by rolandg333** [comment]
which distro ?

**Comment by Schille** [comment]
@Z02X What distro are you talking about? Where did you get this error message from?

**Comment by Schille** [comment]
@Z02X what are the outputs of 
```python
import os
os.getuid()
os.getgid()
```
Do you run the Docker daemon in rootless mode?
Do you run `deck` with a root user on your host?
I'd say the permission errors are caused by faulty ownership on the shared volumes (_/sources_ and _/output_)

**Comment by rolandg333** [comment]
i installed Slackware 15 (on KVM).
 
using the adduser command, i create a new user with uid 1000
and the system has a group 'users' with gid 100

IMHO bug #85 is solved.

**Comment by rolandg333** [comment]
solved

**Comment by Schille** [comment]
Thanks a lot @rolandg333
